development:
  adapter: postgresql
  encoding: utf8
  database: jobboard
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: jobboard
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: jobboard
  pool: 5
  timeout: 5000